export const PRODUCT_ENDPOINT = "/products/"
export const ADD_TO_CART = "/cart/item/"
export const CATEGORIES_ENDPOINT = "/categories/"
export const GET_CART = "/cart"
export const ADDRESS = "/bakery/bakery-addresses/"
export const CHECKOUT = "/orders/checkout/"
export const USER_COUPON = "/user/coupons/"
export const APPLY_COUPON = "/apply/coupon/"