export const PRODUCT_ENDPOINT = "/products/"
export const ADD_TO_CART = "/cart/item/"
export const CATEGORIES_ENDPOINT = "/categories/"
export const GET_CART = "/cart"
export const GET_ADDRESS = "/bakery/bakery-addresses/"
export const CHECKOUT = "/orders/checkout/"